name: NaviTest
options:
  bundleIdPrefix: cz.navitest
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "0.7.0"
    CURRENT_PROJECT_VERSION: "7"
targets:
  NaviTest:
    type: application
    platform: iOS
    sources:
      - path: NaviTest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: cz.navitest.app
        INFOPLIST_FILE: NaviTest/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Manual
    scheme: {}
